### ISSUE TITLE
Healthy Human Heart data consists of 147 batches

### ISSUE THREAD

**Issue by krushnapavan9** [eleozzr/scDML_reproduce#1]
The healthy human heart data that is provided consists of 147 batches. But in the analysis, it was said that after preprocessing, you are left with 140 batches. Can you please provide the information which batches are removed?

**Comment by yuxiaokang-source** [comment]
We deleted the 7 batches that contained the minimum number of cells (['HCAHeart7757637', 'HCAHeart8287125', 'HCAHeart7656537',
                  'HCAHeart7606896', 'HCAHeart7728605', 'HCAHeart7728604',
                  'HCAHeart7728609'])
